# Generated by Django 3.2.16 on 2023-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
