# syntax=docker/dockerfile:1
FROM node:16.13
ENV PYTHONUNBUFFERED=1
WORKDIR /codeFront

CMD  npm install -g npm@8.12.1 && npm start && npm i react-router-dom --save && npm i react-bootstrap --save && npm install --save react-bootstrap bootstrap

